<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Manual</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d85c0933-b9a7-4f37-8fcf-2fc6a649dbfb</testSuiteGuid>
   <testCaseLink>
      <guid>e7f542db-ee3f-4967-8fa0-1931f1a8abf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day1/ManualModeDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f7769649-4a4c-4595-aec5-736f2042a725</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f7769649-4a4c-4595-aec5-736f2042a725</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e1d5dc32-9d23-4a6d-abfd-d6ccc3038c6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f7769649-4a4c-4595-aec5-736f2042a725</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>dfad0d2e-f608-43b7-92c9-6dc50a0cac01</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
