<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>awswaf-captcha-ei 2024-71b</name>
   <tag></tag>
   <elementGuidId>a127c578-e767-4d16-9d02-4ae344c05f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>awswaf-captcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>awswaf-captcha</value>
      <webElementGuid>d563142f-7f22-476e-bd2d-fdaf50fd49e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>982965e3-480e-4417-b0eb-c077c6876398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aws-captcha&quot;)/awswaf-captcha[1]</value>
      <webElementGuid>5b15083a-b521-42b1-86ce-aadef803313e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      <webElementGuid>64ff165a-1e53-4f84-a814-4784286c596b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//awswaf-captcha</value>
      <webElementGuid>88ae4240-7632-4f0d-83eb-ea81d7c14bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
