<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm-024-71b-ae5</name>
   <tag></tag>
   <elementGuidId>5f9ba171-e4ed-4235-9f4c-c9bb135beac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root > div.amzn-captcha-modal > form > div:nth-of-type(6) > div:nth-of-type(2) > #amzn-btn-verify-internal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div[6]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74e01024-d831-4a3a-bfb4-488fbdd5851b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e2e3f83d-e8c7-4012-b774-38165d39bd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amzn-btn-verify-internal</value>
      <webElementGuid>0446434c-4735-40c3-8589-f43abee65201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>699528a9-b2de-469a-a13d-bd0e8f6333a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>203ac03f-7872-4d5d-b0f6-56b5aa4d2619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;root&quot;]/div[@class=&quot;amzn-captcha-modal&quot;]/form[1]/div[6]/div[2]/button[@id=&quot;amzn-btn-verify-internal&quot;]</value>
      <webElementGuid>eec54eca-821b-43e5-a020-97d0f877b3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Day1/Page_Pergipulang JKTA  PDG, 14 Mei 2024, PD_103876/awswaf-captcha-ei 2024-71b</value>
      <webElementGuid>a9f33174-d2a8-4b4f-a292-116dbb3e0b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21bb659e-81d5-406b-8af5-14284432fb97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[6]/div[2]/button</value>
      <webElementGuid>ee1aaa9f-3752-4fb0-adcc-d19da9e7ca70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>5a0e2f0e-43bb-47af-b5b0-279787712521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'amzn-btn-verify-internal' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>2ccc226c-f5bc-4da7-a33b-d036c4cb2b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
