<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas-024-71b-b74</name>
   <tag></tag>
   <elementGuidId>ec10fbeb-7647-4ebe-a1a0-6ac186f3e4af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#root > div.amzn-captcha-modal > form > div:nth-of-type(2) > div > canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div[2]/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>69b47e2d-ebca-4fca-9529-aa93e2267cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>333a11a8-e4f4-40ba-a6cb-6ec3a9ce579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>c133494c-650a-4654-a998-f0cf7a71ddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@id=&quot;root&quot;]/div[@class=&quot;amzn-captcha-modal&quot;]/form[1]/div[2]/div[1]/canvas[1]</value>
      <webElementGuid>ebc246cb-2cb8-45f1-91c9-a0c2adf8bb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Day1/Page_Pergipulang JKTA  PDG, 14 Mei 2024, PD_103876/awswaf-captcha-ei 2024-71b</value>
      <webElementGuid>593cef2a-a4de-4f7f-98fa-2492269e4b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>722cc3d2-3283-4154-8b71-5323fa018207</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[2]/div/canvas</value>
      <webElementGuid>60dd4e09-14d1-4a2e-a53c-9e2c5a97c5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
